### ISSUE TITLE
Error UnhandledPromiseRejectionWarning: TypeError: calc_reading.toFixed is not a function

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.sourceanalytix#113]
I'm getting this error in my log on a day change:

```js
host.bananapim3 | 2020-01-25 00:00:01.105 | error | Caught by controller[4]: (node:13878) UnhandledPromiseRejectionWarning:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by
host.bananapim3 | 2020-01-25 00:00:01.102 | error | Caught by controller[3]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.bananapim3 | 2020-01-25 00:00:01.099 | error | Caught by controller[3]:     at Sourceanalytix.calculation_handler  (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:830:35)
host.bananapim3 | 2020-01-25 00:00:01.041 | error | Caught by controller[3]: (node:13878) UnhandledPromiseRejectionWarning: TypeError: calc_reading.toFixed is not a function
```

This error appears about 16 times in a row.

Cheers,
Zefau

**Comment by DutchmanNL** [comment]
danke da ist Anne unsaubere handling drin, nehme ich mit in meinem jetzige adapter rebuild

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.
