### ISSUE TITLE
Log error at adapter restart

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.sourceanalytix#29]
when adapter is restarted log Is full of error's of promise rejects.

`
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[630]: at <anonymous>
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[630]: at set_zero_val (C:\ioBroker\node_modules\iobroker.sourceanalytix\main.js:565:14)
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[630]: (node:796) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'val' of null
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[629]: (node:796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by r
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[629]: at process._tickCallback (internal/process/next_tick.js:189:7)
host.DESKTOP-LSKTCAN	2019-01-21 21:12:09.960	error	Caught by controller[629]: at <anonymous>
`

**Comment by DutchmanNL** [comment]
fixed in 0.2.27
